name       : telepathy-gabble
version    : 0.18.3
release    : 1
source     :
    - http://telepathy.freedesktop.org/releases/telepathy-gabble/telepathy-gabble-0.18.3.tar.gz : 8ec714607e9bcb8d5a3f44adf871e7b07d5db8e326e47536e74e09cba59989c2
license    : LGPL-2.1
component  : network.im
summary    : telepathy-gabble is a connection manager for the XMPP (Jabber) protocol.
description: |
    telepathy-gabble is a connection manager for the XMPP (Jabber) protocol.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(nice)
    - pkgconfig(sqlite3)
    - pkgconfig(telepathy-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
